apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: synergychat-web
  ports:
    - protocol: TCP
      port: 80 # The port on which the service will listen on
      targetPort: 8080 # The port on which the pods are listening on